from .config import (
    APP_DIR,
    CHROMA_DIR,
    DEFAULT_CHROMA_COLLECTION,
    DEFAULT_EMBEDDING_MODEL,
    DEFAULT_GEMINI_MODEL,
    DEFAULT_LOCAL_LLM,
    DEFAULT_QUESTIONS_PATH,
    PDF_DIR,
    PDF_MD_DIR,
    PROJECT_ROOT,
    RETRIEVAL_CHART_PATH,
    SCAN_DIR,
    SCAN_MD_DIR,
    chunk_json_dirs,
    markdown_dirs,
)

